# Generated by Django 5.2.3 on 2025-06-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('roomSize', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('amenities', models.JSONField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
